### ISSUE TITLE
[error] '"value" argument is out of bounds'

### ISSUE THREAD

**Issue by GiedriusM** [8devices/restserver-demo#7]
buffer.js:1185
    throw new TypeError('"value" argument is out of bounds');
    ^

TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1185:11)
    at Buffer.writeUInt8 (buffer.js:1233:5)
    at Object.result [as Observe] (/home/restserver/restserver-demo/node_modules/coap/lib/option_conv
erter.js:164:9)
    at module.exports.toBinary (/home/restserver/restserver-demo/node_modules/coap/lib/option_convert
er.js:23:39)
    at ObserveWriteStream.setOption (/home/restserver/restserver-demo/node_modules/coap/lib/helpers.j
s:56:16)
    at objects.(anonymous function).resources.(anonymous function).getTLVBuffer (/home/restserver/res
tserver-demo/8dev_emulate/nodes/clientNodeInstance.js:277:28)
    at ResourceInstance.getTLVBuffer (/home/restserver/restserver-demo/8dev_emulate/nodes/resourceIns
tance.js:206:7)
    at ResourceInstance.observation.objects.(anonymous function).resources.(anonymous function).on (/
home/restserver/restserver-demo/8dev_emulate/nodes/clientNodeInstance.js:275:67)
    at emitNone (events.js:111:20)
    at ResourceInstance.emit (events.js:208:7)

**Comment by GiedriusM** [comment]
It looks like observe option may have overflowed the 24 bit observe value:
```
Trigger
16714726
16714727
Trigger
16730893
16730893
Trigger
buffer.js:1185
    throw new TypeError('"value" argument is out of bounds');
```
